### ISSUE TITLE
Move away from JuliaWebAPI.jl

### ISSUE THREAD

**Issue by amellnik** [JuliaDiffEq/DiffEqOnlineServer#2]
I think that since we're going to handle all the scaling and provisioning outside the container, we should just write a very simple server in Mux.jl instead.  Implementing this would also close #1.

**Comment by amellnik** [comment]
Using Mux may be blocked by https://github.com/JuliaWeb/Mux.jl/issues/28.

**Comment by amellnik** [comment]
@ChrisRackauckas -- I'm currently stuck on Mux given it's lack of documentation and illegible code.  If you can figure out how to include custom headers in a response let me know, otherwise I'm switching over to using HttpServer directly.

**Comment by blairn** [comment]
Here is how you do it.

```

   #  Access-Control-Allow-Origin: *
   function withCorsHeader(res)
     headers  = HttpCommon.headers()
     headers["Access-Control-Allow-Origin"] = "*"
     Dict(
       :headers => headers,
       :body=> res
     )
   end
   
   @app service = (
     Mux.defaults,
     page("/data", res -> withCorsHeader(Json.json(getData())))
   )

```

Best of luck!

**Comment by amellnik** [comment]
Done.
