### ISSUE TITLE
Choose a host for a production backend

### ISSUE THREAD

**Issue by amellnik** [JuliaDiffEq/DiffEqOnlineServer#4]
We now have a containerized version of the backend, and need somewhere to stick it.  I started working through gcloud but it's pretty painful, and the docker support is pretty rough at the moment.  [Digitalocean](https://www.digitalocean.com/pricing/ ) seems like an OK option but I don't think there's any easy way to automatically scale it up and down based on usage.  If you don't have any preferences I'll go with either that or Heroku.

**Comment by ChrisRackauckas** [comment]
I have no preferences here, and only limited prior experience with Heroku.

**Comment by amellnik** [comment]
A [wild production server](https://secure-lake-43427.herokuapp.com/squareit/WzEsMiwzXQ==) appears! Right now you can go to  http://app.juliadiffeq.org/ode and paste `http://secure-lake-43427.herokuapp.com/` into the "API URL" box.  I'm going to clean up a few things and possibly rename the heroku app and then have the production front-end always use the production back-end, and only have the API box appear in dev builds.

**Comment by amellnik** [comment]
Actually http://app.juliadiffeq.org/ode should now just work -- currently takes about 7-8 sec to solve the sample equation.  There's a lot more work to do and lots of polishing after that, but all the necessary parts are in-place and working!

**Comment by ChrisRackauckas** [comment]
Hmm, why does it take so long? Is there a way to measure what it is? That equation should take microseconds, so I wonder: is it passing the JSON plot back, or passing the JSON for the solver information (t,u)?

**Comment by amellnik** [comment]
If I understand how Heroku works correctly (looking at [this](https://devcenter.heroku.com/articles/runtime-principles)), it's running `julia mux_server.jl` every time a request comes in, and we incur the JIT startup cost on every single request. (This is the cost of using Heroku, although it comes with the benefit of easy scaling).  I started looking at [precompiling](http://docs.julialang.org/en/release-0.4/manual/modules/) but setting it up (and making sure that every dependency is also precompiled?) sounds pretty hard.

**Comment by ChrisRackauckas** [comment]
We can setup the packages we want to be built into the sysimg.

**Comment by ChrisRackauckas** [comment]
http://docs.julialang.org/en/stable/devdocs/sysimg/

**Comment by amellnik** [comment]
Ah nice -- I'm not sure how the CPU target bit will work with this running in the docker container, but I'll give it a shot and see if I can get it to work.
